### ISSUE TITLE
Unable to upload to remote FTPS site

### ISSUE THREAD

**Issue by dumblerod** [melmorabity/ansible-ftp#1]
When I try to upload to a remote site (in this case an Azure WebApp repo), I get an error message:

Unable to get status for destination /repository: 550 The system cannot find the file specified.

I'm using a playbook like so:

- name: Testing local file upload to remote FTP server
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - local_action:
        module: ftp
        protocol: ftps
        host: somesite.ftp.com
        user: "mycoolusername"
        password: "reallyhardpassword"
        src: testfile.txt
        dest: "/repository/"
        direction: push

Seen this problem or have any ideas?

**Comment by melmorabity** [comment]
I've just made some fixes, could you try the latest snapshot?
