### ISSUE TITLE
module errors

### ISSUE THREAD

**Issue by ddedda** [melmorabity/ansible-ftp#2]
hi . I'd like to transfer a file on to filezilla server, and this is my playbook

[root@centopingtest ansible]# cat copy.ftp.yml 
---
- name: PLAYBOOK COPY RUNNING ON FTP SERVER
  hosts: ftp_server
  gather_facts: no
  tasks:
       - local_action:
           module: ftp
           protocols: ftp
           ftp_mode: passive
           host: 10.227.5.196
           user: terna
           password: terna
           port: 21
           src: /backup/PE_9_config.2020-07-03@11:45:40
           dest: /file_config_bck
           direction: push

[root@centopingtest ansible]# ansible --version
ansible 2.9.9
  config file = /home/user/Desktop/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

when i play this playbook i've the follow errors:

PLAYBOOK: copy.ftp.yml *******************************************************************************************************************
Positional arguments: copy.ftp.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/home/user/Desktop/ansible/hosts',)
forks: 5
1 plays in copy.ftp.yml

PLAY [PLAYBOOK COPY RUNNING ON FTP SERVER] ***********************************************************************************************
META: ran handlers

TASK [ftp] *******************************************************************************************************************************
task path: /home/user/Desktop/ansible/copy.ftp.yml:6
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1594024518.8450358-58209-225072018467028 && echo ansible-tmp-1594024518.8450358-58209-225072018467028="` echo /root/.ansible/tmp/ansible-tmp-1594024518.8450358-58209-225072018467028 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/files/ftp.py
<localhost> PUT /root/.ansible/tmp/ansible-local-58202tsavmnxn/tmp1e2irpzy TO /root/.ansible/tmp/ansible-tmp-1594024518.8450358-58209-225072018467028/AnsiballZ_ftp.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1594024518.8450358-58209-225072018467028/ /root/.ansible/tmp/ansible-tmp-1594024518.8450358-58209-225072018467028/AnsiballZ_ftp.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.6 /root/.ansible/tmp/ansible-tmp-1594024518.8450358-58209-225072018467028/AnsiballZ_ftp.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1594024518.8450358-58209-225072018467028/ > /dev/null 2>&1 && sleep 0'
fatal: [ftp_server -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "dest": "/file_config_bck",
            "direction": "push",
            "ftp_mode": "passive",
            "host": "10.227.5.196",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 21,
            "protocols": "ftp",
            "src": "/backup/PE_9_config.2020-07-03@11:45:40",
            "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "msg": "Unsupported parameters for (ftp) module: protocols Supported parameters include: attributes, backup, content, delimiter, dest, direction, directory_mode, follow, force, ftp_mode, group, host, interval, mode, owner, password, port, protocol, regexp, remote_src, retries, selevel, serole, setype, seuser, src, timeout, tmp_dest, unsafe_writes, user"
}

Do you have an idea?hlep me ...thanks

**Comment by melmorabity** [comment]
> "msg": "Unsupported parameters for (ftp) module: protocols Supported parameters include: attributes, backup, content, delimiter, dest, direction, directory_mode, follow, force, ftp_mode, group, host, interval, mode, owner, password, port, protocol, regexp, remote_src, retries, selevel, serole, setype, seuser, src, timeout, tmp_dest, unsafe_writes, user"

Typical Ansible error message when you specify a bad parameter to a module. You typed "protocols" instead of "protocol" in your module params.
